apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: stream-app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "create", "update", "delete"]
