apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stream-app-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: stream-app-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stream-app-role
