replicaCount: 3

image:
  repository: eddieadi/stream_app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30080

env:
  ENV_VAR: production

imagePullSecrets:
  - name: my-dockerhub-secret
