apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-app-deployment
spec:
  replicas: {{ .Values.streamApp.replicaCount }}
  selector:
    matchLabels:
      app: stream-app
  template:
    metadata:
      labels:
        app: stream-app
    spec:
      serviceAccountName: {{ .Values.streamApp.serviceAccountName }}
      containers:
      - name: stream-app-container
        image: {{ .Values.streamApp.image.repository }}:{{ .Values.streamApp.image.tag }}
        ports:
        - containerPort: 5000
        env:
        - name: ENV_VAR
          value: "production"
        - name: MYSQL_HOST
          value: "mysql-container"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_ROOT_PASSWORD
      imagePullSecrets:
      - name: my-dockerhub-secret
