apiVersion: v1
kind: Service
metadata:
  name: stream-app-service
spec:
  type: NodePort
  selector:
    app: stream-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.streamApp.nodePort }}
